#### 클러스터링_하기

In [1]:
# 라이브러리 호출
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# 그래프상에서 한글을 나타내기 위해 korean_mat 설치
! pip install koreanize-matplotlib
import koreanize_matplotlib

%config InlineBackend.figure_format = 'retina'

# 데이터 불러오기
df = pd.read_csv('/Users/gimdogyun/Desktop/빅데이터_애널리틱스_프로젝트/Big_analytics_project/movie_finished_toFDA_V9.csv')
df.head()

Requirement already satisfied: koreanize-matplotlib in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (0.1.1)
Requirement already satisfied: matplotlib in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from koreanize-matplotlib) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.23 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from matplotlib->koreanize-matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/gimdogyun/Desktop/myenv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

,naver_movie_code,kobis_movie_code,movie_title,release_date,DoW_release,Date,DoW,MoY,D_D,DailyTotal,...,국적평균누적관객수,국적평균스크린수,등급평균관객수,등급평균누적관람객수,등급평균스크린수,7days_before,5days_before,Day_of_release,5days_after,7days_after
0,107374,20142641,나를 잊지 말아요,2016.1.7,Thursday,2016.1.7,Thursday,January,0,612,...,859493,95,9090,596341,79,11,11,13,6,33
1,107374,20142641,나를 잊지 말아요,2016.1.7,Thursday,2016.1.8,Friday,January,1,332,...,859493,95,9090,596341,79,11,11,13,6,33
2,107374,20142641,나를 잊지 말아요,2016.1.7,Thursday,2016.1.9,Saturday,January,2,394,...,859493,95,9090,596341,79,11,11,13,6,33
3,107374,20142641,나를 잊지 말아요,2016.1.7,Thursday,2016.1.10,Sunday,January,3,205,...,859493,95,9090,596341,79,11,11,13,6,33
4,107374,20142641,나를 잊지 말아요,2016.1.7,Thursday,2016.1.11,Monday,January,4,246,...,859493,95,9090,596341,79,11,11,13,6,33

In [2]:
# 2주_누적관객수
# Group by movie title and calculate the cumulative audience count (sum)
df['2주_누적관객수'] = df.groupby('movie_title')['관객수'].transform('sum')

In [3]:
col = [
    'running_time', 'watch_grade',
    '사극', 'SF', '어드벤처', '액션', '범죄', '판타지', '가족', '미스터리', '스릴러', '뮤지컬',
    '코미디', '공포(호러)', '애니메이션', '드라마', '서부극(웨스턴)', '전쟁', '멜로/로맨스', '기타',
    '다큐멘터리', '공연', '성인물(에로)',
    'NTZ_male_score', 'NTZ_female_score', 'NTZ_teen_score', 'NTZ_twenties_score', 
    'NTZ_thirties_score', 'NTZ_forties_score', 'NTZ_fifties_more_score',
    'NTZ_direct_point', 'NTZ_act_point', 'NTZ_story_point', 
    'NTZ_visual_point', 'NTZ_ost_point',
    'director_power', 'actor_power',
    'RV_male', 'RV_female', 'RV_teen', 'RV_twenties', 
    'RV_thirties', 'RV_forties', 'RV_fifties','movie_title'
]

In [4]:
pd.set_option('display.max_columns', None)
df_clustering = df[col].copy()

In [5]:
# log 변환
df_clustering['director_power'] = np.log1p(df_clustering['director_power'])
df_clustering['actor_power'] = np.log1p(df_clustering['actor_power'])

In [6]:
# 비율 피쳐: 30% -> 0.3
ratio_col = ['NTZ_direct_point','NTZ_act_point','NTZ_story_point','NTZ_visual_point','NTZ_ost_point', 'RV_male','RV_female','RV_teen','RV_twenties','RV_thirties','RV_forties','RV_fifties']

# 비율 변환
for col in ratio_col:
    df_clustering[col] = df_clustering[col].str.rstrip('%').astype(float) / 100

In [7]:
df_clustering

,running_time,watch_grade,사극,SF,어드벤처,액션,범죄,판타지,가족,미스터리,스릴러,뮤지컬,코미디,공포(호러),애니메이션,드라마,서부극(웨스턴),전쟁,멜로/로맨스,기타,다큐멘터리,공연,성인물(에로),NTZ_male_score,NTZ_female_score,NTZ_teen_score,NTZ_twenties_score,NTZ_thirties_score,NTZ_forties_score,NTZ_fifties_more_score,NTZ_direct_point,NTZ_act_point,NTZ_story_point,NTZ_visual_point,NTZ_ost_point,director_power,actor_power,RV_male,RV_female,RV_teen,RV_twenties,RV_thirties,RV_forties,RV_fifties,movie_title
0,106,15세이상관람가,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,6.67,6.85,6.76,6.37,6.74,7.12,7.81,0.12,0.50,0.38,0.00,0.00,6.110613,18.038043,0.43,0.57,0.05,0.52,0.27,0.12,0.05,나를 잊지 말아요
1,106,15세이상관람가,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,6.67,6.85,6.76,6.37,6.74,7.12,7.81,0.12,0.50,0.38,0.00,0.00,6.110613,18.038043,0.43,0.57,0.05,0.52,0.27,0.12,0.05,나를 잊지 말아요
2,106,15세이상관람가,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,6.67,6.85,6.76,6.37,6.74,7.12,7.81,0.12,0.50,0.38,0.00,0.00,6.110613,18.038043,0.43,0.57,0.05,0.52,0.27,0.12,0.05,나를 잊지 말아요
3,106,15세이상관람가,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,6.67,6.85,6.76,6.37,6.74,7.12,7.81,0.12,0.50,0.38,0.00,0.00,6.110613,18.038043,0.43,0.57,0.05,0.52,0.27,0.12,0.05,나를 잊지 말아요
4,106,15세이상관람가,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,6.67,6.85,6.76,6.37,6.74,7.12,7.81,0.12,0.50,0.38,0.00,0.00,6.110613,18.038043,0.43,0.57,0.05,0.52,0.27,0.12,0.05,나를 잊지 말아요
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6130,105,15세이상관람가,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,6.03,6.00,5.66,5.93,6.02,6.58,6.11,0.24,0.32,0.20,0.16,0.08,0.000000,0.000000,0.55,0.45,0.09,0.59,0.18,0.09,0.06,애나벨 집으로
6131,105,15세이상관람가,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,6.03,6.00,5.66,5.93,6.02,6.58,6.11,0.24,0.32,0.20,0.16,0.08,0.000000,0.000000,0.55,0.45,0.09,0.59,0.18,0.09,0.06,애나벨 집으로
6132,105,15세이상관람가,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,6.03,6.00,5.66,5.93,6.02,6.58,6.11,0.24,0.32,0.20,0.16,0.08,0.000000,0.000000,0.55,0.45,0.09,0.59,0.18,0.09,0.06,애나벨 집으로
6133,105,15세이상관람가,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,6.03,6.00,5.66,5.93,6.02,6.58,6.11,0.24,0.32,0.20,0.16,0.08,0.000000,0.000000,0.55,0.45,0.09,0.59,0.18,0.09,0.06,애나벨 집으로
6134,105,15세이상관람가,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,6.03,6.00,5.66,5.93,6.02,6.58,6.11,0.24,0.32,0.20,0.16,0.08,0.000000,0.000000,0.55,0.45,0.09,0.59,0.18,0.09,0.06,애나벨 집으로

In [8]:
# min-max scaling
from sklearn.preprocessing import MinMaxScaler

# min-max를 사용해야 할 칼럼: 
min_max_col = ['running_time', 'NTZ_male_score', 'NTZ_female_score', 'NTZ_teen_score', 'NTZ_twenties_score','NTZ_thirties_score', 'NTZ_forties_score', 'NTZ_fifties_more_score', 'director_power','actor_power']

scaler = MinMaxScaler()
for col in min_max_col:
    df_clustering[col] = scaler.fit_transform(df_clustering[[col]])

In [9]:
# watch_grade 더미화
df_clustering = pd.get_dummies(df_clustering, columns=['watch_grade'])
# True, False -> 1, 0: watch_grade
df_clustering.update(df_clustering.select_dtypes(include=['bool']).astype(int))

/var/folders/mz/tk5z94ds1qd9c1jb2p8qys9m0000gn/T/ipykernel_48342/2680656972.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df_clustering.update(df_clustering.select_dtypes(include=['bool']).astype(int))
/var/folders/mz/tk5z94ds1qd9c1jb2p8qys9m0000gn/T/ipykernel_48342/2680656972.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df_clustering.update(df_clustering.select_dtypes(include=['bool']).astype(int))
/var/folders/mz/tk5z94ds1qd9c1jb2p8qys9m0000gn/T/ipykernel_48342/2680656972.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df_clustering.update(df_clustering.select_dtypes(include=['bool']).astype(int))
/var/folders/mz/tk5z94ds1qd9c1jb2p8qys9m0000gn/T/ipykernel_48342/2680656972.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df_clustering.update(df_clustering.select_dtypes(include=['bool']).astype(int))

In [10]:
# movie_title로 groupby 후 평균값으로 대체
df_clustering = df_clustering.groupby('movie_title').mean()

In [11]:
# k-means clustering
from sklearn.cluster import KMeans

# kmeans 모델 생성
kmeans = KMeans(n_clusters=5, random_state=42)
kmeans.fit(df_clustering)

# 군집화 결과 확인
df_clustering['cluster'] = kmeans.labels_
df_clustering['cluster'].value_counts()

# 각 군집별로 평균값
cluster_mean = df_clustering.groupby('cluster').mean()
cluster_mean

,running_time,사극,SF,어드벤처,액션,범죄,판타지,가족,미스터리,스릴러,뮤지컬,코미디,공포(호러),애니메이션,드라마,서부극(웨스턴),전쟁,멜로/로맨스,기타,다큐멘터리,공연,성인물(에로),NTZ_male_score,NTZ_female_score,NTZ_teen_score,NTZ_twenties_score,NTZ_thirties_score,NTZ_forties_score,NTZ_fifties_more_score,NTZ_direct_point,NTZ_act_point,NTZ_story_point,NTZ_visual_point,NTZ_ost_point,director_power,actor_power,RV_male,RV_female,RV_teen,RV_twenties,RV_thirties,RV_forties,RV_fifties,watch_grade_12세이상관람가,watch_grade_15세이상관람가,watch_grade_전체관람가,watch_grade_청소년관람불가
cluster,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0.323167,0.013889,0.013889,0.388889,0.069444,0.000000,0.138889,0.180556,0.013889,0.000000,0.041667,0.222222,0.013889,0.847222,0.013889,0.000000,0.000000,0.027778,0.0,0.013889,0.0,0.0,0.771091,0.802408,0.750656,0.773699,0.759149,0.759581,0.799389,0.094306,0.061111,0.203611,0.181528,0.083611,0.257947,0.769194,0.271250,0.728750,0.017639,0.164722,0.515278,0.279167,0.021806,0.000000,0.000000,1.000000,0.000000
1,0.407216,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.5,0.0,0.741402,0.952527,0.929099,0.906627,0.905556,0.927966,0.889500,0.610000,0.110000,0.195000,0.045000,0.045000,0.000000,0.258375,99.990000,99.990000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,0.000000
2,0.575644,0.025000,0.350000,0.562500,0.912500,0.125000,0.225000,0.025000,0.000000,0.075000,0.000000,0.087500,0.025000,0.037500,0.050000,0.000000,0.000000,0.012500,0.0,0.000000,0.0,0.0,0.655737,0.728369,0.708678,0.622722,0.594226,0.612458,0.744300,0.218625,0.220000,0.190125,0.255250,0.077750,0.376642,0.816163,0.580125,0.419875,0.032500,0.482750,0.268500,0.172750,0.043250,0.712500,0.037500,0.000000,0.250000
3,0.496398,0.030120,0.042169,0.012048,0.253012,0.156627,0.012048,0.006024,0.102410,0.319277,0.000000,0.126506,0.138554,0.006024,0.355422,0.006024,0.012048,0.060241,0.0,0.024096,0.0,0.0,0.652722,0.694349,0.675918,0.614666,0.614984,0.623116,0.737614,0.220060,0.310723,0.249699,0.112108,0.069880,0.263434,0.791505,0.485542,0.514458,0.038916,0.519217,0.240000,0.140482,0.062108,0.000000,0.951807,0.000000,0.048193
4,0.513263,0.022472,0.033708,0.022472,0.033708,0.056180,0.078652,0.022472,0.022472,0.067416,0.011236,0.134831,0.000000,0.011236,0.797753,0.000000,0.011236,0.191011,0.0,0.011236,0.0,0.0,0.729356,0.791163,0.779828,0.720455,0.705029,0.716245,0.788753,0.199213,0.258090,0.272921,0.149326,0.086517,0.351515,0.795960,0.415169,0.584831,0.046742,0.498315,0.234157,0.153708,0.067303,0.786517,0.000000,0.078652,0.134831

In [12]:
# 원래 df에 군집 결과를 합침
df = pd.merge(df, df_clustering['cluster'], on='movie_title', how='left')

In [13]:
df.groupby('cluster')['누적관객수'].mean()

cluster
0    4.574111e+05
1    2.004982e+05
2    1.064282e+06
3    8.693224e+05
4    6.757966e+05
Name: 누적관객수, dtype: float64